2025-03-06 10:09:09,881 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:09:12,434 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:09:33,317 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:10:19,085 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:11:00,111 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:36:12,767 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:36:21,598 INFO: Library startup [in C:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:36:42,120 INFO: Library startup [in C:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:36:55,942 INFO: Library startup [in C:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:37:04,566 INFO: Library startup [in C:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:37:13,890 INFO: Library startup [in C:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:37:57,117 INFO: Library startup [in C:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:38:17,333 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:40:34,056 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:40:37,690 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 10:40:59,613 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 12:08:13,251 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-06 12:08:39,478 INFO: Library startup [in c:\Users\内田万彩子\library_management\utils\logger.py:18]
2025-03-07 09:34:13,982 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 09:34:23,206 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 09:34:33,736 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 09:34:42,918 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 10:25:53,123 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 10:26:02,701 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 10:26:09,162 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 10:26:19,886 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 10:38:29,721 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 10:46:45,051 INFO: Library application startup [in C:\Users\内田万彩子\library_management\utils\logger.py:19]
2025-03-07 10:47:19,192 ERROR: Exception on / [GET] [in C:\Users\内田万彩子\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py:875]
Traceback (most recent call last):
  File "C:\Users\内田万彩子\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1511, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\内田万彩子\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 919, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\内田万彩子\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 915, in full_dispatch_request
    rv = self.preprocess_request()
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\内田万彩子\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\flask\app.py", line 1291, in preprocess_request
    rv = self.ensure_sync(before_func)()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\内田万彩子\library_management\app.py", line 95, in before_request
    if not request.is_secure and app.env != 'development':
                                 ^^^^^^^
AttributeError: 'Flask' object has no attribute 'env'
